In [99]:
import numpy as np
from sklearn.linear_model import LinearRegression
import time

In [222]:
n_features = 2    #特征数
n_samples  = 100000  #样本数

In [223]:
np.random.seed(2020)
w = np.random.normal(0,1,(1,n_features))  #shape: (1,3) , (1,n_features)
b = np.random.normal(0,1,1)               #shape: (1,)

#真实的权重
w_true = np.array([[12,33]])
b_true = np.array([5])

In [224]:
w,b

(array([[-1.76884571,  0.07555227]]), array([-1.1306297]))

In [225]:
np.random.seed(2021)
x = np.random.normal(0,1,(n_samples,n_features)) #x -> shape  (n_samples,n_features)  
y_true = w_true.dot(x.T) + b_true   #y_true -> shape (1,n_samples)

In [235]:
#利用初始化权重预测的结果
y_pre = w.dot(x.T) + b
y_sk=y_true.flatten()
#均方根误差
error = 1/2*np.mean((y_pre-y_true)**2)

In [236]:
y_true,y_sk

(array([[ 45.17166739, -26.63660327, -11.61113147, ...,  33.88940165,
          36.437317  ,  45.4341063 ]]),
 array([ 45.17166739, -26.63660327, -11.61113147, ...,  33.88940165,
         36.437317  ,  45.4341063 ]))

In [237]:
##error,w,b

In [238]:
start=time.time()
m = 10          #用于更新的样本数
epochs = 1000   #迭代的总次数
lr = 0.1       #学习率
err_list = []
e = 1
w_list=[]
b_list=[]
import random
while 1:
    idx = random.sample(list(range(n_samples)),m) #[xx,xx,xx,...]
    x_temp = x[idx,:]
    w = w - lr*1/m*(-1)*(y_true[:,idx]-y_pre[:,idx]).dot(x[idx,:])
    b = b - lr*1/m*(-1)*(y_true[:,idx]-y_pre[:,idx]).sum()
    w_list.append(w)
    b_list.append(b)
    y_pre = w.dot(x.T) + b
    
    #计算误差
    mse = 1/2*np.mean((y_true-y_pre)**2)
    err_list.append(mse)
    
    e += 1
    if e>epochs:
        end=time.time()
        break

In [239]:
end-start

1.772719383239746

In [240]:
w_list

[array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[12., 33.]]),
 array([[1

In [241]:
start=time.time()
model = LinearRegression()
#x.reshape((-1,1))
model.fit(x, y_sk)
print(x.shape,y_sk.shape)
model = LinearRegression().fit(x, y_sk)
end=time.time()

(100000, 2) (100000,)


In [242]:
r_sq = model.score(x, y_sk)
x,y_sk

(array([[ 1.48860905,  0.67601087],
        [-0.41845137, -0.80652081],
        [ 0.55587583, -0.70550429],
        ...,
        [-1.08776729,  1.27098816],
        [ 1.24407218,  0.50025608],
        [ 1.99862957,  0.49850156]]),
 array([ 45.17166739, -26.63660327, -11.61113147, ...,  33.88940165,
         36.437317  ,  45.4341063 ]))

In [243]:
model.coef_

array([12., 33.])

In [244]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 45.17166739 -26.63660327 -11.61113147 ...  33.88940165  36.437317
  45.4341063 ]
